//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorDeProcessos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analises
    {
        public int IDAnalise { get; set; }
        public string Unidades { get; set; }
        public System.DateTime DataEntrega { get; set; }
        public decimal ValorFinanciamento { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal SaldeDevedor { get; set; }
        public string Observacao { get; set; }
        public string TipoAnalise { get; set; }
        public int IDCliente { get; set; }
        public int IDUnidade { get; set; }
    
        public virtual Unidades Unidades1 { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
