//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorDeProcessos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Analises = new HashSet<Analises>();
        }
    
        public int IDCliente { get; set; }
        public int TipoPessoa { get; set; }
        public string Nome { get; set; }
        public string CpfCnpj { get; set; }
        public string Sexo { get; set; }
        public string Profissao { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Renda { get; set; }
        public string EstadoCivil { get; set; }
        public string RegimeCasamento { get; set; }
        public string Conjuge_Cpf { get; set; }
        public string Conjuge_Nome { get; set; }
        public int IDUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analises> Analises { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
