//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorDeProcessos.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Analises = new HashSet<Analises>();
        }
    
        public int IDCliente { get; set; }
		[DisplayName("Tipo de cliente")]
        public int TipoPessoa { get; set; }
		[DisplayName("CPF/CNPJ")]
        public string CpfCnpj { get; set; }
        public string Nome { get; set; }
        public string Sexo { get; set; }
		[DisplayName("Profissão")]
        public string Profissao { get; set; }
		[DisplayName("Data de nascimento")]
		[DisplayFormat(DataFormatString = "{0:d/MM/yyyy}", ApplyFormatInEditMode = true)]
		public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Renda { get; set; }
		[DisplayName("Estado civil")]
        public string EstadoCivil { get; set; }
		[DisplayName("Regime de casamento")]
        public string RegimeCasamento { get; set; }
		[DisplayName("Nome cônjuge")]
		public string Conjuge_Nome { get; set; }
		[DisplayName("CPF Cônjuge")]
        public string Conjuge_Cpf { get; set; }
		[DisplayName("Usuário")]
        public int IDUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analises> Analises { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
