//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorDeProcessos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int IdCliente { get; set; }
        public int IdUnidade { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; }
        public string Sexo { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Profissao { get; set; }
        public float Renda { get; set; }
        public string EstadoCivil { get; set; }
        public string RegimeCasamento { get; set; }
    
        public virtual Unidades Unidades { get; set; }
    }
}
